### ISSUE TITLE
你好，我发现在博客首页里，最新发布 和 点击最多 两个菜单会显示多余的文章，不知道是不是bug

### ISSUE THREAD

**Issue by Gardevoir-mega** [ZHENFENG13/My-Blog-layui#1]
在博客首页里，最新发布 和 点击最多 两个菜单，会显示处于**草稿**状态和**删除**状态的文章，通过菜单种的超链接也可以访问处于**草稿**状态和**删除**状态的文章

**Comment by myzhulin** [comment]
#已解决

**Comment by myzhulin** [comment]
已解决

> 在博客首页里，最新发布 和 点击最多 两个菜单，会显示处于**草稿**状态和**删除**状态的文章，通过菜单种的超链接也可以访问处于**草稿**状态和**删除**状态的文章

已解决

**Comment by wo601814765** [comment]
弱弱的问一句，怎么进入后台啊
